package com.example.Trân.hosme;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.text.HtmlCompat;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import com.example.finalproject_hosme.R;
import com.example.finalproject_hosme.databinding.Activity7Binding;

public class MainActivity7 extends AppCompatActivity {

    Activity7Binding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = Activity7Binding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        loadTerms();
        addEvents();
    }

    private void addEvents() {
        binding.imvBack.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();
            }
        });
    }

    private void loadTerms() {
        String terms =
                "&nbsp;&nbsp;&nbsp;<b> GIỚI THIỆU </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Chào mừng bạn đến với <b>phần mềm HOSME - Đặt lịch khám bệnh</b> (gọi chung là <b>\"Phần mềm\"</b>). Chúng tôi nghiêm túc thực hiện trách nhiệm của mình liên quan đến bảo mật thông tin theo các quy định về bảo vệ bí mật thông tin cá nhân của pháp luật Việt Nam và cam kết tôn trọng quyền riêng tư và sự quan tâm của tất cả người dùng đối với Phần mềm (chúng tôi gọi các dịch vụ chúng tôi cung cấp trên Phần mềm là <b<\"Các Dịch Vụ\"</b>). Chúng tôi nhận biết tầm quan trọng của dữ liệu cá nhân mà bạn đã tin tưởng giao cho chúng tôi và tin rằng chúng tôi có trách nhiệm quản lý, bảo vệ và xử lý dữ liệu cá nhân của bạn một cách thích hợp. Chính Sách Bảo Mật này (<b>\"Chính sách bảo mật\"</b> hay <b>\"Chính sách\"</b>) được thiết kế để giúp bạn hiểu được cách thức chúng tôi thu thập, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân mà bạn đã cung cấp cho chúng tôi và/hoặc lưu giữ về bạn, cho dù là hiện nay hoặc trong tương lai, cũng như để giúp bạn đưa ra quyết định đúng trước khi cung cấp cho chúng tôi bất kỳ dữ liệu cá nhân nào của bạn. Vui lòng đọc kỹ Chính Sách Bảo Mật này. <br><br>" +
                        "&nbsp;&nbsp;&nbsp; \"Dữ liệu cá nhân\" có nghĩa là dữ liệu, dù đúng hay không về một cá nhân mà thông qua đó có thể được xác định được danh tính, hoặc từ dữ liệu đó và thông tin khác mà một tổ chức có hoặc có khả năng tiếp cận. Các ví dụ thường gặp về dữ liệu cá nhân có thể gồm có tên, số chứng minh nhân dân và thông tin liên hệ. <br><br>" +
                        "&nbsp;&nbsp;&nbsp; Bằng việc sử dụng Các Dịch Vụ, đăng ký một tài khoản với chúng tôi, truy cập Phần mềm của chúng tôi, hoặc tiếp cận Các Dịch Vụ, bạn xác nhận và đồng ý rằng bạn chấp nhận các phương pháp, yêu cầu, và/hoặc chính sách được mô tả trong Chính Sách Bảo Mật này, và theo đây bạn đồng ý cho phép chúng tôi thu thập, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân của bạn như mô tả trong đây. NẾU BẠN KHÔNG ĐỒNG Ý CHO PHÉP XỬ LÝ DỮ LIỆU CÁ NH N CỦA BẠN NHƯ MÔ TẢ TRONG CHÍNH SÁCH NÀY, VUI LÒNG KHÔNG SỬ DỤNG CÁC DỊCH VỤ CỦA CHÚNG TÔI HAY TRUY CẬP PHẦN MỀM CỦA CHÚNG TÔI. Nếu chúng tôi thay đổi Chính Sách Bảo Mật của mình, chúng tôi sẽ đăng những thay đổi đó hoặc Chính Sách Bảo Mật sửa đổi trên Phần mềm. Chúng tôi có quyền sửa đổi bổ sung Chính Sách Bảo Mật này vào bất kỳ lúc nào.<br><br> " +
                        "&nbsp;&nbsp;&nbsp;<b> KHI NÀO CHÚNG TÔI SẼ THU THẬP DỮ LIỆU CÁ NHÂN?</b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Chúng tôi sẽ/có thể thu thập dữ liệu cá nhân về bạn khi:<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Bạn đăng ký và/hoặc sử dụng Các Dịch Vụ hoặc truy cập Phần mềm của chúng tôi, hoặc tạo một tài khoản với chúng tôi;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Bạn gửi bất kỳ biểu mẫu nào, bao gồm nhưng không giới hạn ở bảng đăng ký hoặc các bảng khác liên quan đến bất kỳ tiện ích và dịch vụ nào của chúng tôi, bằng hình thức trực tuyến trên Phần mềm hay dưới hình thức khác;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Bạn ký kết bất kỳ thỏa thuận nào hoặc cung cấp các tài liệu hoặc thông tin khác liên quan đến tương tác giữa bạn với chúng tôi, hoặc khi bạn sử dụng các tiện ích và dịch vụ của chúng tôi;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Bạn tương tác với chúng tôi, chẳng hạn như thông qua các cuộc gọi điện thoại (có thể được ghi âm lại), thư từ, fax, gặp gỡ trực tiếp, các nền ứng dụng truyền thông xã hội và email;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Bạn sử dụng các dịch vụ điện tử của chúng tôi, hoặc tương tác với chúng tôi qua Phần mềm của chúng tôi hoặc sử dụng các dịch vụ trên Phần mềm của chúng tôi. Trường hợp này bao gồm, nhưng không giới hạn, thông qua tập tin cookie mà chúng tôi có thể triển khai khi bạn tương tác với các ứng dụng hoặc Phần mềm của chúng tôi;<br><br>   " +
                        "&nbsp;&nbsp;&nbsp;• Bạn thực hiện các giao dịch thông qua Phần mềm hoặc sử dụng các Dịch Vụ của chúng tôi;<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;• Bạn cung cấp ý kiến phản hồi hoặc gửi khiếu nại cho chúng tôi;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Bạn gửi dữ liệu cá nhân của bạn cho chúng tôi vì bất kỳ lý do gì.<br><br>" +
                        "&nbsp;&nbsp;&nbsp; Trên đây chỉ là một số trường hợp phổ biến mà chúng tôi thu thập dữ liệu cá nhân của bạn, không phản ánh hết toàn bộ các trường hợp mà chúng tôi sẽ thu thập dữ liệu cá nhân của bạn.<br><br>" +
                        "&nbsp;&nbsp;&nbsp; Khi bạn truy cập, sử dụng hoặc tương tác với Phần mềm hoặc các ứng dụng di động của chúng tôi, chúng tôi có thể thu thập những thông tin nhất định bằng cách thức tự động hoặc thụ động dùng các công nghệ khác nhau, các công nghệ này có thể được tải về thiết bị của bạn và có thể thiết lập hoặc sửa đổi cài đặt trên thiết bị của bạn. Thông tin mà chúng tôi thu thập có thể bao gồm, nhưng không giới hạn, địa chỉ Giao Thức Internet (IP), hệ điều hành máy tính/thiết bị di động và loại trình duyệt, loại thiết bị di động của bạn, đặc điểm của thiết bị di động, mã danh định duy nhất của thiết bị (UDID) hoặc mã danh định thiết bị di động (MEID) của thiết bị di động của bạn, địa chỉ của một trang web giới thiệu (nếu có), và các trang bạn truy cập trên Phần mềm và các ứng dụng di động của chúng tôi và số lần truy cập. Chúng tôi chỉ có thể thu thập, sử dụng, tiết lộ và/hoặc xử lý thông tin này cho Các Mục Đích (được định nghĩa dưới đây).<br><br>" +
                        "&nbsp;&nbsp;&nbsp; Các ứng dụng di động của chúng tôi có thể thu thập thông tin chính xác về vị trí của thiết bị di động của bạn bằng cách sử dụng các công nghệ như GPS, Wi-Fi, v.v. Chúng tôi thu thập, sử dụng, tiết lộ và/hoặc xử lý thông tin này vì một hoặc nhiều Mục Đích, bao gồm nhưng không giới hạn các dịch vụ dựa trên địa điểm mà bạn yêu cầu hoặc để cung cấp cho bạn những thông tin liên quan tới địa điểm đó hoặc cho phép bạn chia sẻ vị trí của bạn với những đối tác khác của chúng tôi như là một phần của Dịch vụ của chúng tôi Đối với hầu hết các thiết bị di động, bạn có thể hủy việc cho phép chúng tôi thu thập thông tin về vị trí của bạn bằng cách sửa đổi lại mục cài đặt điện thoại. Nếu bạn có thắc mắc về cách vô hiệu dịch vụ định vị vị trí của bạn trên thiết bị di động của bạn, vui lòng liên hệ với nhà cung cấp dịch vụ thiết bị di động hoặc nhà sản xuất thiết bị.<br><br>" +
                        "&nbsp;&nbsp;&nbsp;<b> CHÚNG TÔI SẼ THU THẬP NHỮNG DỮ LIỆU GÌ? </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Dữ liệu cá nhân mà chúng tôi có thể thu thập bao gồm, nhưng không giới hạn:<br><br>  " +
                        "&nbsp;&nbsp;&nbsp; a) Các thông tin về tài khoản được tạo khi người dùng đăng ký trên hệ thống HOSME<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Họ tên, Giới tính, Ngày tháng năm sinh <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Mật khẩu<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Địa chỉ email (nếu có)<br><br> " +
                        "&nbsp;&nbsp;&nbsp; b) Các thông tin hồ sơ khám bệnh mà người dùng tạo trên hệ thống HOSME<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Họ tên, Giới tính, Ngày tháng năm sinh, Địa chỉ <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Số điện thoại<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Địa chỉ email và CCCD (nếu có)<br><br> " +
                        "&nbsp;&nbsp;&nbsp; c) Các thông tin phiếu đăng ký khám bệnh khi người dùng đăng ký trên hệ thống HOSME<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;• Cơ sở y tế, Dịch vụ, Chuyên khoa, Ngày và Giờ khám<br><br>" +
                        "&nbsp;&nbsp;&nbsp; d) Các thông tin thanh toán<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;• Mã giao dịch thanh toán, Mã phiếu <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Thông tin về số tiền thanh toán, ngày giờ thực hiện thanh toán<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Các thông tin liên quan khác<br><br> " +
                        "&nbsp;&nbsp;&nbsp;<b> TRUY CẬP PHẦN MỀM </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Như với hầu hết các trang web hay ứng dụng khác, thiết bị của bạn gửi thông tin có thể gồm có dữ liệu cá nhân về bạn, được một máy chủ web ghi lại khi bạn truy cập Phần mềm của chúng tôi. Thông tin này thường bao gồm nhưng không giới hạn địa chỉ IP, hệ điều hành, tên/phiên bản trình duyệt của máy tính của bạn, ngày và giờ truy cập, và đôi khi là một “cookie” để giúp Phần mềm của chúng tôi ghi nhớ lần truy cập cuối cùng của bạn. Nếu bạn đăng nhập, thông tin này được liên kết với tài khoản cá nhân của bạn. Thông tin này cũng được đưa vào các số liệu thống kê ẩn danh để giúp chúng tôi hiểu được khách truy cập sử dụng trang web của chúng tôi như thế nào.<br><br>" +
                        "&nbsp;&nbsp;&nbsp;<b> CỘNG ĐỒNG & HỖ TRỢ </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Chúng tôi cung cấp dịch vụ hỗ trợ khách hàng thông qua email, và tổng đài điện thoại và bằng các mẫu đơn lấy ý kiến phản hồi. Để cung cấp dịch vụ hỗ trợ khách hàng, chúng tôi sẽ yêu cầu bạn cung cấp địa chỉ email. Ngoài thông tin này, chúng tôi không yêu cầu bất kỳ dữ liệu cá nhân nào để cung cấp dịch vụ hỗ trợ khách hàng. Chúng tôi chỉ sử dụng thông tin đã nhận từ các yêu cầu hỗ trợ khách hàng, bao gồm nhưng không giới hạn ở, địa chỉ email, đối với các dịch vụ hỗ trợ khách hàng và chúng tôi không chuyển nhượng hay chia sẻ thông tin này với bất kỳ bên thứ ba nào.<br><br>  " +
                        "&nbsp;&nbsp;&nbsp; Bạn cũng có thể đăng các thắc mắc trong Phần mềm của chúng tôi. Chúng tôi sẽ phản hồi các thắc mắc của bạn một cách sớm nhất, đồng thời chúng tôi được toàn quyền sử dụng các vấn đề thắc mắc bạn đã gửi cho chúng tôi, để chúng tôi cải tiến nội dung và dịch vụ của chúng tôi, và/hoặc cập nhật vào nội dung thắc mắc, mà chúng tôi không cần có bất cứ 1 thông báo hay xin phép dưới bất kỳ hình thức nào với bạn.<br><br>" +
                        "&nbsp;&nbsp;&nbsp;<b> KHẢO SÁT </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Đôi khi, chúng tôi có thể yêu cầu thông tin từ người dùng thông qua các cuộc khảo sát. Việc tham gia các cuộc khảo sát này là hoàn toàn tự nguyện và do đó bạn có thể lựa chọn có tiết lộ thông tin của bạn cho chúng tôi hay không. Thông tin được yêu cầu có thể bao gồm nhưng không giới hạn, thông tin liên lạc (chẳng hạn như địa chỉ email của bạn), và thông tin nhân khẩu (chẳng hạn như sở thích hoặc độ tuổi). Thông tin khảo sát có thể được sử dụng cho mục đích theo dõi hoặc cải thiện việc sử dụng và sự hài lòng đối với Các Dịch Vụ và/hoặc sẽ được chuyển cho các bên thứ ba, các đối tác của chúng tôi, để chúng tôi có thể cải thiện, nâng cao chất lượng, nội dung, dịch vụ và quản lý hoặc có biện pháp khác dựa trên khảo sát.<br><br>" +
                        "&nbsp;&nbsp;&nbsp;<b> CHÚNG TÔI SỬ DỤNG THÔNG TIN BẠN CUNG CẤP CHO CHÚNG TÔI NHƯ THẾ NÀO? </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Chúng tôi có thể thu thập, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân của bạn vì một hoặc nhiều mục đích sau đây:<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;• Để xem xét và/hoặc xử lý bảng đăng ký hay giao dịch của bạn với chúng tôi hoặc giao dịch hay thư từ của bạn với các bên thứ ba qua Các Dịch Vụ;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để quản lý, điều hành, cung cấp, quản lý việc bạn sử dụng Các Dịch Vụ và/hoặc truy cập Phần mềm của chúng tôi, cũng như quan hệ và tài khoản người dùng của bạn với chúng tôi;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để quản lý, điều hành, quản trị và cung cấp cho bạn cũng như tạo điều kiện cung cấp Các Dịch Vụ của chúng tôi, bao gồm, nhưng không giới hạn ở ghi nhớ ưu tiên của bạn;<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;• Để điều chỉnh trải nghiệm của bạn thông qua các Dịch Vụ bằng cách hiển thị nội dung theo mối quan tâm và ưu tiên của bạn, cung cấp một phương thức nhanh hơn cho bạn truy cập thông tin tài khoản của bạn và gửi thông tin cho chúng tôi và cho phép chúng tôi liên hệ với bạn, nếu cần;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để đáp ứng, xử lý, giải quyết hoặc hoàn tất một giao dịch và/hoặc đáp ứng các yêu cầu của bạn đối với các tiện ích và dịch vụ nhất định và thông báo cho bạn về các vấn đề dịch vụ và các hoạt động tài khoản bất thường;<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;• Để thực thi các <b>Điều Khoản Dịch Vụ</b> và <b>Quy Định Sử Dụng</b> của chúng tôi hoặc bất kỳ thỏa thuận giấy phép người dùng cuối nào áp dụng; <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để bảo vệ sự an toàn cá nhân và các quyền, tài sản hoặc sự an toàn của người khác;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để duy trì và quản lý bất kỳ bản cập nhật phần mềm nào và/hoặc các bản cập nhật khác và sự hỗ trợ có thể được yêu cầu tùy lúc nhằm đảm bảo các Dịch Vụ của chúng tôi hoạt động suôn sẻ;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Để giải quyết hoặc tạo điều kiện dịch vụ khách hàng, thực hiện các chỉ thị của bạn, giải quyết hoặc trả lời bất kỳ thắc mắc nào được gửi bởi (hoặc nhằm được gửi bởi) bạn hoặc thay mặt bạn; <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để liên hệ với bạn qua điện thoại, tin nhắn văn bản và/hoặc tin nhắn fax, email và/hoặc thư hoặc cách thức khác nhằm mục đích quản trị và/hoặc quản lý quan hệ của bạn với chúng tôi hoặc việc bạn sử dụng các Dịch Vụ của chúng tôi, chẳng hạn như nhưng không giới hạn ở việc truyền đạt thông tin hành chính cho bạn liên quan đến các Dịch Vụ của chúng tôi. Bạn xác nhận và đồng ý rằng sự liên lạc như thế của chúng tôi có thể là theo cách gửi thư qua đường bưu điện, tài liệu hoặc thông báo cho bạn, có thể gồm có tiết lộ dữ liệu cá nhân nhất định về bạn để cung cấp các tài liệu đó cũng như trên bao bì/phong bì;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để thông báo cho bạn khi một người dùng khác đã sử dụng thông tin hoặc tài khoản của bạn để đăng ký sử dụng các Dịch Vụ trên Phần mềm của chúng tôi;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Để tiến hành các hoạt động nghiên cứu, phân tích và phát triển (bao gồm nhưng không giới hạn ở phân tích dữ liệu, khảo sát, phát triển và/hoặc lập đặc tính tiện ích và dịch vụ), để phân tích cách thức bạn sử dụng các Dịch Vụ của chúng tôi, để cải thiện các Dịch Vụ hoặc tiện ích của chúng tôi và/hoặc để cải thiện trải nghiệm khách hàng của bạn; <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để cho phép quảng cáo và các đợt kiểm tra và khảo sát khác, ngoài những hoạt động khác, xác thực quy mô và thành phần của đối tượng người dùng, và hiểu được trải nghiệm của họ với các Dịch Vụ của Phần mềm.<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Trường hợp bạn cho phép trước, vì mục đích tiếp thị, gửi cho bạn qua các phương thức liên lạc khác nhau chẳng hạn như đường bưu điện, email, các dịch vụ dựa trên địa điểm hoặc cách khác, thông tin và tài liệu tiếp thị và quảng bá liên quan đến các tiện ích và/hoặc dịch vụ (bao gồm, nhưng không giới hạn ở, các tiện ích và/hoặc dịch vụ của các bên thứ ba mà chúng tôi có thể hợp tác hoặc liên kết) có thể bán, tiếp thị hoặc quảng bá, cho dù các tiện ích hoặc dịch vụ đó tồn tại vào lúc này hoặc được tạo ra trong tương lai;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Để đáp ứng các thủ tục pháp lý hoặc để tuân thủ hoặc theo quy định của bất kỳ điều luật hiện hành nào, các yêu cầu của chính phủ hoặc cơ quan quản lý có thẩm quyền của bất kỳ khu vực nào; <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để lập số liệu thống kê và nghiên cứu đáp ứng yêu cầu báo cáo và/hoặc duy trì sổ sách nội bộ hoặc theo quy chế;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để thực hiện quy trình tìm hiểu và xác minh hoặc các hoạt động sàng lọc khác (bao gồm, nhưng không giới hạn ở, kiểm tra lý lịch) tuân thủ các nghĩa vụ theo quy định pháp luật hoặc quản lý hoặc các thủ tục kiểm soát rủi ro của chúng tôi, có thể được pháp luật yêu cầu hoặc có thể đã được chúng tôi áp dụng;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Để kiểm tra các Dịch Vụ của chúng tôi hoặc hoạt động của Phần mềm; <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để ngăn chặn hoặc điều tra bất kỳ hoạt động gian lận, phi pháp, thiếu sót hay hành vi sai trái nào, cho dù có liên quan đến việc bạn sử dụng các Dịch Vụ của chúng tôi hay không hay bất kỳ vấn đề nào phát sinh từ quan hệ của bạn với chúng tôi, và cho dù có nghi ngờ về những hoạt động bên trên hay không;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Để lưu trữ, lập máy chủ, sao lưu (cho dù là vì mục đích khôi phục sau thảm họa hoặc mục đích khác) đối với dữ liệu cá nhân của bạn, cho dù là trong hay ngoài khu vực của bạn;;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Để xử lý và/hoặc tạo thuận tiện cho một <b>giao dịch tài sản kinh doanh</b> hoặc một <b>giao dịch tài sản kinh doanh tiềm năng</b>, trường hợp giao dịch đó liên quan đến chúng tôi như một bên tham gia và/hoặc liên quan đến một đối tác hay công ty liên kết của chúng tôi như một bên tham gia. (“Giao dịch tài sản kinh doanh” là các giao dịch mua, bán, cho thuê, sáp nhập, hợp nhất hoặc bất kỳ hoạt động mua lại, thanh lý hay tài trợ nào của một tổ chức hoặc một phần của một tổ chức hoặc của bất kỳ hoạt động kinh doanh hay tài sản nào của một tổ chức); <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Bất kỳ mục đích nào mà chúng tôi thông báo cho bạn tại thời điểm xin sự cho phép của bạn. (gọi chung là “các Mục Đích”).<br><br>" +
                        "&nbsp;&nbsp;&nbsp; Vì các mục đích mà chúng tôi sẽ hoặc có thể thu thập, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân của bạn phụ thuộc vào hoàn cảnh hiện có, mục đích đó có thể không xuất hiện bên trên. Tuy nhiên, chúng tôi sẽ thông báo cho bạn biết mục đích khác đó tại thời điểm xin sự cho phép của bạn, trừ phi việc xử lý dữ liệu áp dụng mà không có sự đồng ý của bạn là được phép theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân hoặc theo quy định pháp luật.<br><br> " +
                        "&nbsp;&nbsp;&nbsp;<b> CHIA SẺ THÔNG TIN TỪ CÁC DỊCH VỤ </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Trong một chừng mực nào đó các Dịch Vụ của chúng tôi cho phép người dùng có thể xem được thông tin của bạn, việc này chỉ và không nằm ngoài mục đích tra cứu, xem và xác nhận lại số hồ sơ của người dùng đó đã tồn tại trên hệ thống dữ liệu của chúng tôi, để hoàn tất các thao tác trong việc đăng ký và sử dụng các dịch vụ trên Phần mềm, để không gây ảnh hưởng, nhầm lẫn, trùng lắp đến dữ liệu của chúng tôi. Trong một giao dịch điển hình, người dùng có thể truy cập tên, số hồ sơ, địa chỉ email của người dùng khác. Các Điều Khoản Dịch Vụ của chúng tôi yêu cầu người dùng nào đang giữ dữ liệu cá nhân của một người dùng khác (\"Bên Nhận\") phải:<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Đảm bảo chỉ dùng để tra cứu lại số hồ sơ về tài khoản của mình;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Chỉ sử dụng đúng số hồ sơ có các thông tin cá nhân là của mình; <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Chịu hoàn toàn thiệt hại và trách nhiệm pháp lý về việc chọn sử dụng số hồ sơ và thông tin cá nhân của mình;<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Tuân thủ tất cả các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân áp dụng;<br><br> " +
                        "&nbsp;&nbsp;&nbsp;• Cho phép người dùng kia (\"Bên Tiết Lộ\") xóa tên mình ra khỏi cơ sở dữ liệu của Bên Nhận; <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Cho phép Bên Tiết Lộ xem thông tin gì đã được Bên Nhận thu thập về họ.<br><br>" +
                        "&nbsp;&nbsp;&nbsp;<b> CHÚNG TÔI BẢO VỆ THÔNG TIN KHÁCH HÀNG BẰNG CÁCH NÀO? </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Chúng tôi thực hiện các biện pháp bảo mật khác nhau để đảm bảo sự an toàn của dữ liệu cá nhân của bạn trên các hệ thống của chúng tôi. Dữ liệu cá nhân của bạn được lưu trữ đằng sau các mạng bảo mật trên các hệ thống của chúng tôi. Chúng tôi sẽ duy trì dữ liệu cá nhân tuân theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân và/hoặc các điều luật hiện hành khác. Có nghĩa là, chúng tôi sẽ hủy hoặc xóa thông tin nhận dạng ra khỏi dữ liệu cá nhân của bạn ngay khi hợp lý để giả định rằng:<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;• Việc lưu giữ dữ liệu cá nhân đó không còn phục vụ mục đích thu thập dữ liệu cá nhân đó nữa; <br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Việc lưu giữ không còn cần thiết cho bất kỳ mục đích hợp pháp hay mục đích kinh doanh nào. Nếu bạn ngừng sử dụng Phần mềm, hoặc quyền của bạn được sử dụng Phần mềm và/hoặc Các Dịch Vụ đã chấm dứt, chúng tôi có thể tiếp tục lưu, sử dụng và/hoặc tiết lộ dữ liệu cá nhân của bạn tuân theo Chính Sách Bảo Mật này và các nghĩa vụ của chúng tôi theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân. Tùy theo luật áp dụng, chúng tôi có thể tiêu hủy dữ liệu cá nhân của bạn một cách an toàn mà không cần thông báo trước cho bạn.<br><br>" +
                        "&nbsp;&nbsp;&nbsp;<b> CHÚNG TÔI CÓ TIẾT LỘ THÔNG TIN MÀ HỌ THU THẬP TỪ KHÁCH TRUY CẬP CHO CÁC BÊN BÊN NGOÀI HAY KHÔNG? </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Trong quá trình thực hiện chúng tôi sẽ hoặc có thể cần phải tiết lộ dữ liệu cá nhân của bạn cho các đối tác và/hoặc các công ty liên kết của chúng tôi, và/hoặc các bên thứ ba khác, cho dù ở bên trong hay bên ngoài Việt Nam, vì một hay nhiều Mục Đích nói trên. Các nhà cung cấp dịch vụ bên thứ ba, đối tác và/hoặc các công ty liên kết sẽ xử lý dữ liệu cá nhân của bạn thay mặt chúng tôi vì một hoặc nhiều Mục Đích nói trên.<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;<b> THÔNG TIN THU THẬP BỞI CÁC BÊN THỨ BA </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Chúng tôi, và các bên thứ ba, có thể thỉnh thoảng cung cấp các bản tải về ứng dụng phần mềm cho bạn sử dụng trên hoặc thông qua Các Dịch Vụ. Những ứng dụng này có thể truy cập riêng, và cho phép một bên thứ ba xem, thông tin nhận dạng của bạn, chẳng hạn như tên, ID người dùng của bạn, Địa Chỉ IP của máy tính của bạn hoặc thông tin khác. Ngoài ra, các ứng dụng này có thể yêu cầu bạn cung cấp thêm thông tin trực tiếp cho các bên thứ ba. Các tiện ích hoặc dịch vụ của bên thứ ba được cung cấp thông qua các ứng dụng này không thuộc sở hữu hay quyền kiểm soát của Phần mềm. Bạn nên đọc các điều khoản và các chính sách khác được công bố bởi các bên thứ ba đó trên trang web của họ hoặc nơi khác.<br><br>" +
                        "&nbsp;&nbsp;&nbsp;<b> LOẠI TRỪ TRÁCH NHIỆM VỀ NGHĨA VỤ BẢO MẬT VÀ CÁC TRANG WEB BÊN THỨ BA </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; CHÚNG TÔI KHÔNG ĐẢM BẢO TÍNH BẢO MẬT ĐỐI VỚI DỮ LIỆU CÁ NH N VÀ/HOẶC THÔNG TIN KHÁC MÀ BẠN CUNG CẤP TRÊN CÁC TRANG WEB CỦA BÊN THỨ BA. Chúng tôi thực hiện các biện pháp bảo mật khác nhau để duy trì sự an toàn của dữ liệu cá nhân của bạn mà chúng tôi lưu giữ hoặc kiểm soát. Dữ liệu cá nhân của bạn được lưu đằng sau các mạng bảo mật trên hệ thống của chúng tôi. Khi bạn đăng ký các dịch vụ, giao dịch, hoặc truy cập dữ liệu cá nhân của bạn, chúng tôi đề nghị sử dụng một máy chủ bảo mật. Tất cả dữ liệu cá nhân hoặc thông tin cá nhân bạn cung cấp sẽ được mã hóa vào các cơ sở dữ liệu của chúng tôi để chỉ được truy cập như mô tả bên trên.<br><br>" +
                        "&nbsp;&nbsp;&nbsp; Nhằm cung cấp cho bạn giá trị gia tăng, chúng tôi có thể chọn các trang web của bên thứ ba khác nhau để liên kết. Chúng tôi cũng có thể tham gia các quan hệ cùng tiếp thị và các quan hệ khác để cung cấp các dịch vụ và tính năng khác cho bạn. Những trang được liên kết này có các chính sách về quyền riêng tư cũng như các biện pháp bảo mật riêng và độc lập. Ngay cả khi bên thứ ba đó có liên kết với chúng tôi, chúng tôi cũng không kiểm soát các trang web được liên kết này, mỗi trang đó có các phương pháp bảo vệ quyền riêng tư và thu thập dữ liệu riêng biệt, độc lập với chúng tôi. Dữ liệu thu thập bởi các đối tác cùng tiếp thị của chúng tôi hoặc các trang web bên thứ ba (ngay cả khi được cung cấp trên hoặc thông qua Phần mềm của chúng tôi) có thể không được nhận bởi chúng tôi.<br><br>  " +
                        "&nbsp;&nbsp;&nbsp; Do đó chúng tôi không chịu trách nhiệm hay trách nhiệm pháp lý đối với nội dung, các biện pháp bảo mật (hoặc sự thiếu biện pháp bảo mật) và các hoạt động của các trang web được liên kết này. Những trang web được liên kết này chỉ vì sự thuận tiện cho bạn và do đó bạn tự chịu trách nhiệm khi truy cập chúng. Tuy nhiên, chúng tôi tìm cách bảo vệ tính toàn vẹn của Phần mềm của chúng tôi và các liên kết được đặt trên từng trang web đó và do đó chúng tôi hoan nghênh ý kiến phản hồi về các trang web được liên kết này (bao gồm, nhưng không giới hạn ở, nếu một trang web cụ thể không hoạt động).<br><br>" +
                        "&nbsp;&nbsp;&nbsp;<b> BẠN CÓ THỂ RÚT TÊN, XÓA TÊN, YÊU CẦU TRUY CẬP HOẶC ĐIỀU CHỈNH THÔNG TIN BẠN ĐÃ CUNG CẤP CHO CHÚNG TÔI BẰNG CÁCH NÀO? </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Rút Tên và Rút Lại Sự Đồng Ý<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;• Để sửa đổi đăng ký email của bạn, vui lòng thông báo cho chúng tôi qua tổng đài<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Bạn có thể rút lại sự đồng ý cho phép thu thập, sử dụng và/hoặc tiết lộ dữ liệu cá nhân của bạn mà chúng tôi đang lưu giữ hoặc kiểm soát bằng cách thông báo cho chúng tôi qua tổng đài<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Một khi chúng tôi nhận được yêu cầu rõ ràng của bạn về việc rút lại sự đồng ý đề cập bên trên và xác minh danh tính của bạn, chúng tôi sẽ giải quyết yêu cầu này và sau đó sẽ không thu thập, sử dụng và/hoặc tiết lộ dữ liệu cá nhân của bạn theo cách được cho biết trong yêu cầu của bạn. Nếu chúng tôi không thể xác minh làm rõ hiểu được yêu cầu của bạn.<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Tuy nhiên, việc bạn rút lại sự đồng ý có thể dẫn đến những hậu quả pháp lý nhất định phát sinh việc đó cũng như ảnh hưởng đến việc sử dụng các dịch vụ và tiện tích của bạn trên Phần mềm của chúng tôi. Về vấn đề này, tùy vào mức độ của yêu cầu đó, nó có thể có nghĩa là chúng tôi sẽ không thể tiếp tục cung cấp các Dịch Vụ cho bạn, chúng tôi có thể cần phải chấm dứt quan hệ hiện tại của bạn và/hoặc giao dịch của bạn với chúng tôi, v.v., tùy trường hợp, mà chúng tôi sẽ thông báo cho bạn.<br><br> " +
                        "&nbsp;&nbsp;&nbsp; Yêu Cầu Truy Cập và/hoặc Sửa Dữ Liệu Cá Nhân<br><br>" +
                        "&nbsp;&nbsp;&nbsp;• Nếu bạn đã đăng ký một tài khoản với chúng tôi, cá nhân bạn có thể truy cập và/hoặc sửa dữ liệu cá nhân của bạn mà chúng tôi đang lưu giữ hoặc kiểm soát thông qua trang Chỉnh Sửa Thông Tin Tài Khoản trên Phần mềm của chúng tôi. Nếu bạn chưa đăng ký tài khoản với chúng tôi, cá nhân bạn có thể yêu cầu truy cập và/hoặc sửa dữ liệu cá nhân của bạn mà chúng tôi đang lưu giữ hoặc kiểm soát bằng cách gửi yêu cầu qua email cho nhân viên Quản lý dữ liệu của chúng tôi tại địa chỉ email info@medpro.vn. Chúng tôi sẽ cần có đủ thông tin từ bạn để xác định danh tính của bạn cũng như bản chất yêu cầu của bạn để có thể giải quyết yêu cầu của bạn. <br><br>" +
                        "&nbsp;&nbsp;&nbsp; Chúng tôi cũng sẽ không tính một khoản phí nào cho bạn đối với việc giải quyết và xử lý yêu cầu truy cập dữ liệu cá nhân của bạn.<br><br>" +
                        "&nbsp;&nbsp;&nbsp; Chúng tôi có quyền từ chối sửa dữ liệu cá nhân của bạn theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân, trường hợp các điều luật đó yêu cầu và/hoặc cho phép một tổ chức từ chối sửa dữ liệu cá nhân trong các trường hợp như thế và/hoặc các đối tác của chúng tôi từ chối yêu chỉnh sửa thông tin cá nhân của bạn.<br><br> " +
                        "&nbsp;&nbsp;&nbsp;<b> THẮC MẮC, QUAN NGẠI HOẶC KHIẾU NẠI? LIÊN HỆ VỚI CHÚNG TÔI </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Nếu bạn có bất kỳ thắc mắc hoặc quan ngại nào về các phương pháp bảo vệ quyền riêng tư của chúng tôi hoặc các giao dịch của bạn với các Dịch Vụ hoặc Nếu bạn có bất kỳ khiếu nại hay khiếu kiện nào về cách chúng tôi xử lý dữ liệu cá nhân của bạn hoặc về cách chúng tôi tuân thủ các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân, vui lòng liên hệ qua email hoặc tổng đài.<br><br>  " +
                        "&nbsp;&nbsp;&nbsp;<b> ĐIỀU KHOẢN CHUNG </b><br><br>" +
                        "&nbsp;&nbsp;&nbsp; Chính Sách Bảo Mật này là một phần không tách rời với Điều Khoản Dịch Vụ và Quy Định Sử Dụng Phần Mềm của chúng tôi. Xin vui lòng đọc thêm các Điều Khoản Dịch Vụ và Quy Định Sử Dụng để hiểu rõ các quy định, điều khoản, chính sách và hướng dẫn của chúng tôi trước khi bạn truy cập Phần mềm và/hoặc đăng ký và/hoặc sử dụng các Dịch Vụ trên Phần mềm của chúng tôi.<br><br>" +
                        "&nbsp;&nbsp;&nbsp; TÔI ĐÃ ĐỌC CHÍNH SÁCH NÀY VÀ ĐỒNG Ý VỚI TẤT CẢ CÁC ĐIỀU KHOẢN CÓ TRONG NỘI DUNG BÊN TRÊN VÀ BẤT KỲ BẢN CHỈNH SỬA NÀO CỦA NỘI DUNG BÊN TRÊN SAU NÀY. BẰNG VIỆC TIẾP TỤC TRUY CẬP VÀ SỬ DỤNG PHẦN MỀM, TÔI HIỂU RẰNG TÔI ĐANG TẠO RA MỘT CHỮ KÝ ĐIỆN TỬ MÀ NÓ CÓ GIÁ TRỊ VÀ HIỆU LỰC TƯƠNG TỰ NHƯ CHỮ KÝ TÔI KÝ BẰNG TAY <br><br>" +
                        "&nbsp;&nbsp;&nbsp;<i> Cập nhật gần nhất: 15/03/2024.</i><br><br>";

        // Sử dụng HTML để hiển thị đoạn văn trong TextView
        binding.termsTextView.setText(HtmlCompat.fromHtml(terms, HtmlCompat.FROM_HTML_MODE_LEGACY));
    }

}